name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello Diya! GitHub Actions is working!"