name : PR Validation Pipeline
on: 
  pull_request: # Create PR-> Run Workflow
    branches:
      - main

jobs:
  validation:

  runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4 #uses (Use an Action that someone has already written.)
                                  # actions/checkout (This is an Action created by GitHub. Internally it performs a git clone for you.)
                                  # @v4 (Use version 4 of the action. This is important because it ensures that you are using a stable version of the action that has been tested and verified to work correctly.)